[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lerxml"
version = "0.1.0"
description = "Tools for parsing and validating LER XML"
authors = [
    { name = "Your Name" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lxml",
    "xmlschema",
    "pyyaml",
    "pyschematron",
    "shapely",
]

[project.scripts]
lerxml = "lerxml.cli:main"

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy"
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
lerxml = ["**/*"]

[tool.ruff]
line-length = 100
